# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Thu Jun 13 22:01:55 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from CurveCPU import *
from CurveMemory import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

OFFSET = 60
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        #MainWindow.resize(587, 494)
        MainWindow.setFixedSize(587, 494 + OFFSET)
        MainWindow.setAnimated(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(-1, 0, 591, 481 + OFFSET))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(591, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(591, 16777215))
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))

        self.tab_sys = QtGui.QWidget()
        self.tab_sys.setObjectName(_fromUtf8("tab_sys"))
        self.label_CPU = QtGui.QLabel(self.tab_sys)
        self.label_CPU.setGeometry(QtCore.QRect(20, 10, 259, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_CPU.setFont(font)
        self.label_CPU.setTextFormat(QtCore.Qt.AutoText)
        self.label_CPU.setObjectName(_fromUtf8("label_CPU"))
        self.label_OS = QtGui.QLabel(self.tab_sys)
        self.label_OS.setGeometry(QtCore.QRect(20, 239, 391, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_OS.setFont(font)
        self.label_OS.setTextFormat(QtCore.Qt.AutoText)
        self.label_OS.setObjectName(_fromUtf8("label_OS"))
        self.pushButton_shutdown = QtGui.QPushButton(self.tab_sys)
        self.pushButton_shutdown.setGeometry(QtCore.QRect(360, 385 + OFFSET, 91, 31))
        self.pushButton_shutdown.setObjectName(_fromUtf8("pushButton_shutdown"))
        self.pushButton_reboot = QtGui.QPushButton(self.tab_sys)
        self.pushButton_reboot.setGeometry(QtCore.QRect(470, 385 + OFFSET, 91, 31))
        self.pushButton_reboot.setObjectName(_fromUtf8("pushButton_reboot"))
        self.label_1 = QtGui.QLabel(self.tab_sys)
        self.label_1.setGeometry(QtCore.QRect(32, 43, 90, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_1.setFont(font)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.label_2 = QtGui.QLabel(self.tab_sys)
        self.label_2.setGeometry(QtCore.QRect(32, 81, 100, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label = QtGui.QLabel(self.tab_sys)
        self.label.setGeometry(QtCore.QRect(32, 120, 130, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_CPU_name = QtGui.QLabel(self.tab_sys)
        self.label_CPU_name.setGeometry(QtCore.QRect(180, 42, 391, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_CPU_name.setFont(font)
        self.label_CPU_name.setObjectName(_fromUtf8("label_CPU_name"))
        self.label_CPU_type = QtGui.QLabel(self.tab_sys)
        self.label_CPU_type.setGeometry(QtCore.QRect(180, 80, 391, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_CPU_type.setFont(font)
        self.label_CPU_type.setObjectName(_fromUtf8("label_CPU_type"))
        self.label_CPU_freq = QtGui.QLabel(self.tab_sys)
        self.label_CPU_freq.setGeometry(QtCore.QRect(180, 119, 391, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_CPU_freq.setFont(font)
        self.label_CPU_freq.setObjectName(_fromUtf8("label_CPU_freq"))
        self.label_3 = QtGui.QLabel(self.tab_sys)
        self.label_3.setGeometry(QtCore.QRect(33, 283, 80, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.tab_sys)
        self.label_5.setGeometry(QtCore.QRect(33, 360, 120, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_4 = QtGui.QLabel(self.tab_sys)
        self.label_4.setGeometry(QtCore.QRect(33, 321, 110, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_OS_type = QtGui.QLabel(self.tab_sys)
        self.label_OS_type.setGeometry(QtCore.QRect(180, 282, 391, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_OS_type.setFont(font)
        self.label_OS_type.setObjectName(_fromUtf8("label_OS_type"))
        self.label_OS_version = QtGui.QLabel(self.tab_sys)
        self.label_OS_version.setGeometry(QtCore.QRect(180, 320, 391, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_OS_version.setFont(font)
        self.label_OS_version.setObjectName(_fromUtf8("label_OS_version"))
        self.label_GCC_version = QtGui.QLabel(self.tab_sys)
        self.label_GCC_version.setGeometry(QtCore.QRect(180, 359, 391, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_GCC_version.setFont(font)
        self.label_GCC_version.setObjectName(_fromUtf8("label_GCC_version"))
        self.tabWidget.addTab(self.tab_sys, _fromUtf8(""))

        self.tab_mem = QtGui.QWidget()
        self.tab_mem.setObjectName(_fromUtf8("tab_mem"))
        self.label_CPU_usage = QtGui.QLabel(self.tab_mem)
        self.label_CPU_usage.setGeometry(QtCore.QRect(20, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_CPU_usage.setFont(font)
        self.label_CPU_usage.setTextFormat(QtCore.Qt.AutoText)
        self.label_CPU_usage.setObjectName(_fromUtf8("label_CPU_usage"))
        self.label_memory = QtGui.QLabel(self.tab_mem)
        self.label_memory.setGeometry(QtCore.QRect(20, 225 + OFFSET / 1.5, 321, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_memory.setFont(font)
        self.label_memory.setTextFormat(QtCore.Qt.AutoText)
        self.label_memory.setObjectName(_fromUtf8("label_memory"))
        #self.qwtPlot_CPU = Qwt5.QwtPlot(self.tab_mem)
        self.qwtPlot_CPU = CpuPlot(self.tab_mem)
        self.qwtPlot_CPU.setGeometry(QtCore.QRect(20, 40, 551, 171))
        self.qwtPlot_CPU.setObjectName(_fromUtf8("qwtPlot_CPU"))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_CPU_Total = QtGui.QLabel(self.tab_mem)
        self.label_CPU_Total.setGeometry(QtCore.QRect(20, 213, 321, 31))
        self.label_CPU_Total.setFont(font)
        self.label_CPU_Total.setTextFormat(QtCore.Qt.AutoText)
        self.label_CPU_Total.setObjectName(_fromUtf8("label_CPU_usage"))
        self.label_CPU_Cores = QtGui.QLabel(self.tab_mem)
        self.label_CPU_Cores.setGeometry(QtCore.QRect(20, 235, 321, 31))
        self.label_CPU_Cores.setFont(font)
        self.label_CPU_Cores.setTextFormat(QtCore.Qt.AutoText)
        self.label_CPU_Cores.setObjectName(_fromUtf8("label_CPU_cores"))
        #self.qwtPlot_memory = Qwt5.QwtPlot(self.tab_mem)
        self.qwtPlot_memory = MemoryPlot(self.tab_mem)
        self.qwtPlot_memory.setGeometry(QtCore.QRect(20, 255 + OFFSET / 1.5, 551, 151))
        self.qwtPlot_memory.setObjectName(_fromUtf8("qwtPlot_memory"))
        self.label_mem_usage = QtGui.QLabel(self.tab_mem)
        self.label_mem_usage.setGeometry(QtCore.QRect(20, 405 + OFFSET / 1.5, 551, 31))
        self.label_mem_usage.setFont(font)
        self.label_mem_usage.setTextFormat(QtCore.Qt.AutoText)
        self.label_mem_usage.setObjectName(_fromUtf8("label_mem_usage"))
        self.label_swap_usage = QtGui.QLabel(self.tab_mem)
        self.label_swap_usage.setGeometry(QtCore.QRect(20, 405 + 22 + OFFSET / 1.5, 551, 31))
        self.label_swap_usage.setFont(font)
        self.label_swap_usage.setTextFormat(QtCore.Qt.AutoText)
        self.label_swap_usage.setObjectName(_fromUtf8("label_swap_usage"))
        self.tabWidget.addTab(self.tab_mem, _fromUtf8(""))

        self.tab_proc = QtGui.QWidget()
        self.tab_proc.setObjectName(_fromUtf8("tab_proc"))
        self.label_process = QtGui.QLabel(self.tab_proc)
        self.label_process.setGeometry(QtCore.QRect(20, 387 + OFFSET, 551, 60))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(11)
        self.label_process.setFont(font)
        self.label_process.setObjectName(_fromUtf8("label_process"))
        self.tableWidget_process = QtGui.QTableWidget(self.tab_proc)
        self.tableWidget_process.setGeometry(QtCore.QRect(20, 10, 551, 381 + OFFSET))
        self.tableWidget_process.setFrameShadow(QtGui.QFrame.Plain)
        self.tableWidget_process.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_process.setRowCount(0)
        self.tableWidget_process.setColumnCount(6)
        self.tableWidget_process.setObjectName(_fromUtf8("tableWidget_process"))
        self.tableWidget_process.verticalHeader().setSortIndicatorShown(True)
        self.pushButton_kill = QtGui.QPushButton(self.tab_proc)
        self.pushButton_kill.setGeometry(QtCore.QRect(480, 400 + OFFSET, 91, 31))
        self.pushButton_kill.setObjectName(_fromUtf8("pushButton_kill"))
        self.tabWidget.addTab(self.tab_proc, _fromUtf8(""))

        self.tab_mod = QtGui.QWidget()
        self.tab_mod.setObjectName(_fromUtf8("tab_mod"))
        self.tableWidget_module = QtGui.QTableWidget(self.tab_mod)
        self.tableWidget_module.setGeometry(QtCore.QRect(20, 10, 551, 391 + OFFSET))
        self.tableWidget_module.setFrameShadow(QtGui.QFrame.Plain)
        self.tableWidget_module.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_module.setRowCount(0)
        self.tableWidget_module.setColumnCount(3)
        self.tableWidget_module.setObjectName(_fromUtf8("tableWidget_module"))
        self.tableWidget_module.verticalHeader().setSortIndicatorShown(True)
        self.label_module = QtGui.QLabel(self.tab_mod)
        self.label_module.setGeometry(QtCore.QRect(20, 405 + OFFSET, 551, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(11)
        self.label_module.setFont(font)
        self.label_module.setObjectName(_fromUtf8("label_module"))
        self.tabWidget.addTab(self.tab_mod, _fromUtf8(""))

        self.tab_about = QtGui.QWidget()
        self.tab_about.setObjectName(_fromUtf8("tab_about"))
        self.label_about = QtGui.QLabel(self.tab_about)
        self.label_about.setGeometry(QtCore.QRect(20, 20, 551, 450))
        self.label_about.setObjectName(_fromUtf8("label_about"))
        self.label_about.setAlignment(QtCore.Qt.AlignTop)
        self.tabWidget.addTab(self.tab_about, _fromUtf8(""))

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.label_status = QtGui.QLabel(self.statusbar)
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setGeometry(QtCore.QRect(0, -4, 551, 31))

        self.retranslateUi(MainWindow)
        #self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "TaskManager", None))
        self.label_CPU.setText(_translate("MainWindow", "CPU Information", None))
        self.label_OS.setText(_translate("MainWindow", "OS Information", None))
        self.pushButton_shutdown.setText(_translate("MainWindow", "Shutdown", None))
        self.pushButton_reboot.setText(_translate("MainWindow", "Reboot", None))
        self.label_1.setText(_translate("MainWindow", "CPU Name:", None))
        self.label_2.setText(_translate("MainWindow", "CPU Type: ", None))
        self.label.setText(_translate("MainWindow", "CPU Freqency:", None))
        self.label_CPU_name.setText(_translate("MainWindow", "Unknown", None))
        self.label_CPU_type.setText(_translate("MainWindow", "Unknown", None))
        self.label_CPU_freq.setText(_translate("MainWindow", "Unknown", None))
        self.label_3.setText(_translate("MainWindow", "OS Type:", None))
        self.label_5.setText(_translate("MainWindow", "GCC Version:", None))
        self.label_4.setText(_translate("MainWindow", "OS Version:", None))
        self.label_OS_type.setText(_translate("MainWindow", "Unknown", None))
        self.label_OS_version.setText(_translate("MainWindow", "Unknown", None))
        self.label_GCC_version.setText(_translate("MainWindow", "Unknown", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sys), _translate("MainWindow", "System", None))
        self.label_CPU_usage.setText(_translate("MainWindow", "CPU History", None))
        self.label_CPU_Total.setText(_translate("MainWindow", "Total: ", None))
        self.label_CPU_Cores.setText(_translate("MainWindow", "CPU0: ", None))
        self.label_memory.setText(_translate("MainWindow", "Memory and Swap History", None))
        self.label_mem_usage.setText(_translate("MainWindow", "Memory Usage:", None))
        self.label_swap_usage.setText(_translate("MainWindow", "Swap Usage:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mem), _translate("MainWindow", "Resource", None))
        self.label_process.setText(_translate("MainWindow", "Process Stat.", None))
        self.pushButton_kill.setText(_translate("MainWindow", "Kill", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_proc), _translate("MainWindow", "Process", None))
        self.label_module.setText(_translate("MainWindow", "Module Stat.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mod), _translate("MainWindow", "Module", None))
        self.label_about.setText(_translate("MainWindow", "About", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_about), _translate("MainWindow", "About", None))
        #self.statusbar.message(_translate("MainWindow", "Time:N/A   CPU:N/A   Memory:N/A", None))
        self.label_status.setText(_translate("MainWindow", "<span style=\"color:fuchsia\">Status</span>", None))

from PyQt4 import Qwt5
